from fastapi import FastAPI

app = FastAPI()

## '/docs' is a default endpoint where documentation is auto-generated by FastAPI

## @app decorator is used to create a '/hello' route
# '/hello' is an endpoint
@app.get("/hello")
def hello():
    return {'message':'Hello World!!'}

@app.get("/about")
def about():
    return {'message':'My name is Nishchay Singla'}